#!/usr/bin/env bash

set -e 

INSTALL=${1:-'0'}
NAME_PROJECTS_DIR="sites2"
USERNAME=$(whoami)

[ "$INSTALL" = '1' ] && TESTMODE=0 || TESTMODE=1

ETC_DIR=/etc
BIN_DIR=/usr/local/bin
APACHE_CFG_DIR=/etc/apache2/sites-available

HOMEDIR="$HOME"
PROJECTS_DIR="$HOMEDIR/$NAME_PROJECTS_DIR"
LOG_DIR="$PROJECTS_DIR/log"
WWW_DIR="$PROJECTS_DIR/www"
VHOST_DIR="$WWW_DIR/vhost"
LOCALHOST_DIR="$WWW_DIR/localhost"

display_before_exit() {
  PATH="BIN_DIR":$PATH
  export $PATH
  echo -e "\nAdd $BIN_DIR to your PATH variables"
}

echo_type_error() {
  echo "$1"
}

create_dir() {
  local NEWDIR=${1:-''}
  local USE_SUDO=${2:-''}
  if [ "$NEWDIR" = '' ]; then 
    echo_type_error 'Error: create empty dirname catalog'
    exit 1
  fi
  if [ -d "$NEWDIR" ]; then
    [ "$USE_SUDO" = '1' ] && USE_SUDO=sudo || USE_SUDO=''
    $USE_SUDO mkdir -p "$NEWDIR"
  fi
}

create_dirs_for_test_mode() {
  local ROOT=''
  if [ "$TESTMODE" = '1' ]; then 
    ROOT="$PROJECTS_DIR/root"
    ETC_DIR="$ROOT/$ETC_DIR"
    BIN_DIR="$ROOT/$BIN_DIR"
    APACHE_CFG_DIR="$ROOT/$APACHE_CFG_DIR"
    create_dir "$ETC_DIR"
    create_dir "$BIN_DIR"
    create_dir "$APACHE"
  fi
}

create_projects_dirs() {
  create_dirs_for_test_mode
  create_dir "$LOG_DIR"
  create_dir "$WWW_DIR"
  create_dir "$VHOST_DIR"
  create_dir "$LOCALHOST_DIR"
}

copy_files() {
}

initial_setup() {
}

change_vars_for_test_mode
create_projects_dirs
copy_files
initial_setup
restart_web_server_after_install
display_before_exit

exit 0